Feature - Final Project - Implement Screen Login
mvn-annguyen-dn/RxSwift_FinalProject pull request #8
Opened 2023-01-18 02:43 UTC by mvn-phonghuynh-dn

2023-01-31 09:25 UTC, mvn-quocdoan-dn commented on RxSwift_Template/Models/Core/ApiNetWorkManager.swift
>                  }
Chuyên nghiệp lên nào

2023-02-02 04:33 UTC, mvn-quocdoan-dn commented on RxSwift_Template/Models/Core/ApiNetWorkManager.swift
> +            }
Đồng nhất type of error, please

2023-02-02 04:35 UTC, mvn-annguyen-dn requested changes
- separate code by particular functionalities
- when u make task that is related to UI, attach screenshot UI
@mvn-phonghuynh-dn  please fix my comments, Thanks

2023-02-02 10:16 UTC, mvn-quocdoan-dn reviewed
@mvn-luongtran-dn Hi luong, please check my comment. Thanks!

2023-02-02 10:16 UTC, mvn-quocdoan-dn commented on RxSwift_Template/AppDelegate/AppDelegate.swift
> +    let tabbarController = UITabBarController()
Remove please

2023-02-02 10:16 UTC, mvn-quocdoan-dn commented on RxSwift_Template/Models/Scheme/Example.swift
> +     }
??

2023-02-02 10:16 UTC, mvn-quocdoan-dn commented on RxSwift_Template/Models/Scheme/Example.swift
> +     }
??

2023-02-02 10:18 UTC, mvn-annguyen-dn requested changes
- Create BaseViewController is made common function (for instance: showAlertError, handleSomething) for all of viewcontroller
- Check my comments, Thanks
@mvn-luongtran-dn

2023-02-02 10:18 UTC, mvn-annguyen-dn commented on RxSwift_Template/Models/Core/LoginTarget.swift
> +            fatalError(ApiError.unknown.localizedDescription)
shouldn't use fatalError => throw

2023-02-06 02:17 UTC, merged